[
{ id: 1, l_name: '秋月', f_name: '律子', l_kana: 'あきづき', f_kana: 'りつこ' },
{ id: 2, l_name: '天海', f_name: '春香', l_kana: 'あまみ', f_kana: 'はるか' },
{ id: 3, l_name: '伊吹', f_name: '翼', l_kana: 'いぶき', f_kana: 'つばさ' },
{ id: 4, l_name: 'エミリー', f_name: 'スチュアート', l_kana: 'えみりー', f_kana: 'すちゅあーと' },
{ id: 5, l_name: '大神', f_name: '環', l_kana: 'おおがみ', f_kana: 'たまき' },
{ id: 6, l_name: '春日', f_name: '未来', l_kana: 'かすが', f_kana: 'みらい' },
{ id: 7, l_name: '我那覇', f_name: '響', l_kana: 'がなは', f_kana: 'ひびき' },
{ id: 8, l_name: '菊地', f_name: '真', l_kana: 'きくち', f_kana: 'まこと' },
{ id: 9, l_name: '如月', f_name: '千早', l_kana: 'きさらぎ', f_kana: 'ちはや' },
{ id: 10, l_name: '北上', f_name: '麗花', l_kana: 'きたかみ', f_kana: 'れいか' },
{ id: 11, l_name: '北沢', f_name: '志保', l_kana: 'きたざわ', f_kana: 'しほ' },
{ id: 12, l_name: '木下', f_name: 'ひなた', l_kana: 'きのした', f_kana: 'ひなた' },
{ id: 13, l_name: '高坂', f_name: '海美', l_kana: 'こうさか', f_kana: 'うみ' },
{ id: 14, l_name: '佐竹', f_name: '美奈子', l_kana: 'さたけ', f_kana: 'みなこ' },
{ id: 15, l_name: '四条', f_name: '貴音', l_kana: 'しじょう', f_kana: 'たかね' },
{ id: 16, l_name: '篠宮', f_name: '可憐', l_kana: 'しのみや', f_kana: 'かれん' },
{ id: 17, l_name: '島原', f_name: 'エレナ', l_kana: 'しまばら', f_kana: 'えれな' },
{ id: 18, l_name: 'ジュリア', f_name: '', l_kana: 'じゅりあ', f_kana: '' },
{ id: 19, l_name: '周防', f_name: '桃子', l_kana: 'すおう', f_kana: 'ももこ' },
{ id: 20, l_name: '高槻', f_name: 'やよい', l_kana: 'たかつき', f_kana: 'やよい' },
{ id: 21, l_name: '高山', f_name: '紗代子', l_kana: 'たかやま', f_kana: 'さよこ' },
{ id: 22, l_name: '田中', f_name: '琴葉', l_kana: 'たなか', f_kana: 'ことは' },
{ id: 23, l_name: '天空橋', f_name: '朋花', l_kana: 'てんくうばし', f_kana: 'ともか' },
{ id: 24, l_name: '徳川', f_name: 'まつり', l_kana: 'とくがわ', f_kana: 'まつり' },
{ id: 25, l_name: '所', f_name: '恵美', l_kana: 'ところ', f_kana: 'めぐみ' },
{ id: 26, l_name: '豊川', f_name: '風花', l_kana: 'とよかわ', f_kana: 'ふうか' },
{ id: 27, l_name: '中谷', f_name: '育', l_kana: 'なかたに', f_kana: 'いく' },
{ id: 28, l_name: '永吉', f_name: '昴', l_kana: 'ながよし', f_kana: 'すばる' },
{ id: 29, l_name: '七尾', f_name: '百合子', l_kana: 'ななお', f_kana: 'ゆりこ' },
{ id: 30, l_name: '二階堂', f_name: '千鶴', l_kana: 'にかいどう', f_kana: 'ちづる' },
{ id: 31, l_name: '野々原', f_name: '茜', l_kana: 'ののはら', f_kana: 'あかね' },
{ id: 32, l_name: '萩原', f_name: '雪歩', l_kana: 'はぎわら', f_kana: 'ゆきほ' },
{ id: 33, l_name: '箱崎', f_name: '星梨花', l_kana: 'はこざき', f_kana: 'せりか' },
{ id: 34, l_name: '馬場', f_name: 'このみ', l_kana: 'ばば', f_kana: 'このみ' },
{ id: 35, l_name: '福田', f_name: 'のり子', l_kana: 'ふくだ', f_kana: 'のりこ' },
{ id: 36, l_name: '双海', f_name: '亜美', l_kana: 'ふたみ', f_kana: 'あみ' },
{ id: 37, l_name: '双海', f_name: '真美', l_kana: 'ふたみ', f_kana: 'まみ' },
{ id: 38, l_name: '星井', f_name: '美希', l_kana: 'ほしい', f_kana: 'みき' },
{ id: 39, l_name: '舞浜', f_name: '歩', l_kana: 'まいはま', f_kana: 'あゆむ' },
{ id: 40, l_name: '真壁', f_name: '瑞希', l_kana: 'まかべ', f_kana: 'みずき' },
{ id: 41, l_name: '松田', f_name: '亜利沙', l_kana: 'まつだ', f_kana: 'ありさ' },
{ id: 42, l_name: '三浦', f_name: 'あずさ', l_kana: 'みうら', f_kana: 'あずさ' },
{ id: 43, l_name: '水瀬', f_name: '伊織', l_kana: 'みなせ', f_kana: 'いおり' },
{ id: 44, l_name: '宮尾', f_name: '美也', l_kana: 'みやお', f_kana: 'みや' },
{ id: 45, l_name: '最上', f_name: '静香', l_kana: 'もがみ', f_kana: 'しずか' },
{ id: 46, l_name: '望月', f_name: '杏奈', l_kana: 'もちづき', f_kana: 'あんな' },
{ id: 47, l_name: '百瀬', f_name: '莉緒', l_kana: 'ももせ', f_kana: 'りお' },
{ id: 48, l_name: '矢吹', f_name: '可奈', l_kana: 'やぶき', f_kana: 'かな' },
{ id: 49, l_name: '横山', f_name: '奈緒', l_kana: 'よこやま', f_kana: 'なお' },
{ id: 50, l_name: '伴田', f_name: '路子', l_kana: 'はんだ', f_kana: 'ろこ' },
].each do |character|
  Character.find_or_create_by(
    id: character[:id],
    l_name: character[:l_name],
    f_name: character[:f_name],
    l_kana: character[:l_kana],
    f_kana: character[:f_kana],
  )
end
