dimains = ['us','be','in','aichijp','akitajp','chibajp','ehimejp','fukuijp','fukuokajp','fukushimajp','gifujp','gunmajp','hiroshimajp','hokkaidojp','hyogojp','ibarakijp','ishikawajp','kagawajp','kagoshimajp','kanagawajp','kochijp','kumamotojp','kyotojp','miejp','miyagijp','miyazakijp','naganojp','nagasakijp','narajp','niigatajp','oitajp','okayamajp','okinawajp','osakajp','sagajp','saitamajp','shigajp','shimanejp','shizuokajp','tochigijp','tokushimajp','tokyojp','tottorijp','toyamajp','wakayamajp','yamagatajp','yamaguchijp','yamanashijp','bz','cc','comco','netco','nomco','ws','acjp','cojp','edjp','gojp','orjp','id','tv','tw','la','vc','mn','cz','mx','ac','hn','am','sc']
dimains.each do |domain|
  Domain.find_or_create_by(name: domain, url: 'https://www.onamae.com')
end

dimains = ['email','company','group','ltd','network','support','nagoya','yokohama','okinawa','ryukyu','center','digital','marketing','services','ventures','コム','click','kim','link','onl','social','vip','bet','futbol','pictures','rocks','partners','dance','family','live','ninja','rip','studio','agency','band','beer','bid','blog','business','casa','city','cooking','country','directory','education','equipment','exposed','fashion','fishing','fit','football','fyi','gallery','garden','gift','graphics','gratis','horse','ink','institute','international','lighting','management','party','photography','photos','reisen','report','reviews','rodeo','run','school','schule','science','soccer','solutions','supplies','supply','surf','systems','technology','tips','today','trade','uno','video','vodka','webcam','wedding','wiki','yoga','airforce','army','auction','cam','consulting','date','democrat','engineer','faith','forsale','gives','haus','immobilien','kaufen','market','moda','navy','pub','rehab','republican','review','sale','software','vet','academy','accountant','associates','bargains','bike','boutique','builders','buzz','cab','cafe','camera','camp','cards','care','cash','catering','chat','cheap','church','cleaning','clothing','coffee','community','computer','construction','contractors','cool','deals','direct','discount','dog','domains','download','enterprises','estate','events','exchange','express','fail','farm','fish','fitness','florist','foundation','gifts','glass','gripe','guide','guru','help','house','immo','industries','kitchen','kiwi','land','limited','loan','lol','mba','media','mom','money','ooo','parts','photo','pics','plumbing','plus','productions','properties','racing','rentals','repair','rest','sarl','shoes','show','singles','solar','team','tools','town','toys','training','vision','watch','win','works','wtf','zone','actor','attorney','dentist','lawyer','black','degree','london','mortgage','tattoo','apartments','bingo','capital','careers','claims','clinic','coach','codes','condos','coupons','cruises','dating','delivery','dental','diamonds','engineering','expert','finance','financial','flights','fund','furniture','golf','healthcare','hockey','holdings','holiday','insure','jewelry','lease','legal','limo','maison','memorial','pizza','recipes','restaurant','salon','sexy','surgery','tax','taxi','tennis','theater','tienda','tours','university','vacations','vegas','viajes','villas','vin','voyage','wine','bar','college','cricket','global','kyoto','rent','health','adult','best','ceo','christmas','energy','porn','sex','accountants','credit','gold','investments','loans','tires','audio','blackfriday','casino','creditcard','diet','flowers','guitars','hiphop','property','hiv','movie','game','hosting','juegos','theatre','storage','rich','auto','car','cars','protection','security']
dimains.each do |domain|
  Domain.find_or_create_by(name: domain, url: 'https://www.onamae.com')
end

domains = ['com','net','press','space','work','pw','site','xyz','club','info','online','tokyo','top','website','biz','life','me','mobi','shop','fun','tech','org','pro','cloud','asia','bio','green','host','organic','world','blue','pink','red','co','style','art','design','games','love','news','日本語
jp','promo','men','ski','jp','poker','ai']
dimains.each do |domain|
  Domain.find_or_create_by(name: domain, url: 'https://www.onamae.com')
end

